jasypt:
  encryptor:
    password: liuweijw

server:
  tomcat:
    max-threads: 500
    min-spare-threads: 50

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    remote: true        #是否是开启缓存
    host: 120.79.84.65
    port: 6379
    password: ENC(PTeXGrRsjpGNJraZDhcQL16hs6lucVuMrpSnm0nMknkziK0hJAuhmePOQ4WixafhCaqhRjWwIsA=)
  rabbitmq:
    host: 120.79.84.65
    port: 5672
    username: ENC(e7wHwRdme5270KAOt4vRakfj/xn3Km5E)
    password: ENC(Lzx8NVEstZlX88Y/780BwVJ9TkFP3gFe)
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

cache:
  redis:
    expiration: 3600

ribbon:
  eager-load:
    enabled: true
    clients: system-auth-server,business-admin-server,business-pay-server,project-ditu-server,business-wechat-server
  Httpclient:
    enable: false
  OkHttp:
    enable: true
  ReadTimeout: 20000
  ConnectTimeout: 20000

feign:
  hystrix:
    enabled: true
  okhttp:
    enable: true
  httpclient:
    enable: false
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false
