server:
  port: 2003

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(4UMotM7Ik00exfgsySSQQA==)
    password: ENC(xfw5qpm1bVdSEvGSFsP+nVlfsvJaEZVJt/eDeHa4SM0=)
    url: ENC(c5fOKqEjalvg5op9xcpIRF++fKg8JXTNaEOn9wFEZv5nVN5sImxQjpuhyA8DYYP+rfKxaeBpRjpez2Js/GmXyd8gG+d8gvA0OZ5aBNMs04Qd3+hDmBJfbImFuBU85jiyWfh3l5PL1l3KWlkUWCnS0yoFWm1D6UeKssS3WAUGT9o=)
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: ENC(jcJhwP+VV8fPYfAO5Nw1VRWkmwp6g/9i)
    port: 5672
    username: ENC(t1i+4uELN+o7PZQ9MCTKHOWIUkCY4rL6)
    password: ENC(OmhRNBSPvefBvk7JGk7cEPC4Lk912Cfb)
  zipkin:
    rabbitmq:
      queue: ENC(587DwkeAxTsJBQsFI4URlw==)
  sleuth:
    sampler:
      percentage: 1.0

logging:
  config: classpath:logback.xml
