server:
  port: 1011

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(YXXxUQzO2qaxX2bJzDNKZg==)
    password: ENC(iIR6UImHnGfe4GOkWBFxtw==)
    url: jdbc:mysql://172.18.201.87:3306/fw-cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

zipkin:
  collector:
    rabbitmq:
      addresses: 172.18.201.87:5672
      password: ENC(Lzx8NVEstZlX88Y/780BwVJ9TkFP3gFe)
      username: ENC(e7wHwRdme5270KAOt4vRakfj/xn3Km5E)
      queue: zipkin
  storage:
    type: mysql
