server:
  port: 1011

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(4UMotM7Ik00exfgsySSQQA==)
    password: ENC(xfw5qpm1bVdSEvGSFsP+nVlfsvJaEZVJt/eDeHa4SM0=)
    url: jdbc:mysql://127.0.0.1:3306/fw-cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

zipkin:
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5672
      password: ENC(OmhRNBSPvefBvk7JGk7cEPC4Lk912Cfb)
      username: ENC(t1i+4uELN+o7PZQ9MCTKHOWIUkCY4rL6)
      queue: zipkin
  storage:
    type: mysql
