server:
  port: 4001

redis:
  cache:
    expiration: 3600

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(YXXxUQzO2qaxX2bJzDNKZg==)
    password: ENC(iIR6UImHnGfe4GOkWBFxtw==)
    url: jdbc:mysql://120.79.84.65:3306/business-jdd-dmc?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

logging:
  config: classpath:logback.xml
