server:
  port: 4001

redis:
  cache:
    expiration: 3600

spring:
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(4UMotM7Ik00exfgsySSQQA==)
    password: ENC(xfw5qpm1bVdSEvGSFsP+nVlfsvJaEZVJt/eDeHa4SM0=)
    url: ENC(ihrBJ/kfDWZyu4Vn2nyfXNsMZvxjOm5r5y+3irMR0PDt8K/oxgkazO0m0C19D6rMmT6uepMYuCBUi7UGiloBQMEDcebzyUoBkMZrFiSTQmJXPMXcEhQgDeFK4NktiBi8A2wvYMrj1hCC033cTQ8awzcTEMKMu7HVB0A49cTDhJQ=)
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  zipkin:
    rabbitmq:
      queue: ENC(587DwkeAxTsJBQsFI4URlw==)
  sleuth:
    sampler:
      percentage: 0.2

logging:
  config: classpath:logback.xml
